version: "3.9"
volumes:
  jenkins-home:
  jenkins-test-report:
services:
  jenkins:
    image: luxis/jenkins-calculator
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8085:8080"
    - "50005:50000"
    volumes:
      - "jenkins-home:/var/jenkins_home/"
      - "jenkins-test-report:/var/reports/"
      - "/var/run/docker.sock:/var/run/docker.sock"
